export enum Icons {
  IconClock = "icon-clock",
  IconClose = "icon-close",
  IconDog = "icon-dog",
  IconEdit = "icon-edit",
  IconFlag = "icon-flag",
  IconHanger = "icon-hanger",
  IconInfo = "icon-info",
  IconKeyboard = "icon-keyboard",
  IconLinkExternal = "icon-link-external",
  IconMedia = "icon-media",
  IconPlay = "icon-play",
  IconRankings = "icon-rankings",
  IconRestart = "icon-restart",
  IconSave = "icon-save",
  IconSettings = "icon-settings",
  IconUp = "icon-up",
  IconUsers = "icon-users",
  IconVolumeOff = "icon-volume-off",
  IconVolumeUp = "icon-volume-up",
  IconWallet = "icon-wallet",
}
